USE mydb;

CREATE TABLE IF NOT EXISTS spam_history (
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    userId    BIGINT,
    text       TEXT,
    category   VARCHAR(10),
    prediction DOUBLE,
    createdAt DATETIME,
    isDeleted BOOLEAN DEFAULT FALSE
);

INSERT INTO spam_history (userId, text, category, prediction, createdAt, isDeleted) VALUES
(1, 'Congratulations! You have won a $1000 gift card. Click here to claim now!', 'spam', 0.97, NOW(), false),
(1, 'Hey, are we still meeting for lunch tomorrow?', 'ham', 0.04, NOW(), false),
(1, 'URGENT: Your account has been compromised. Verify your details immediately.', 'spam', 0.95, NOW(), false),
(1, 'reminder: team standup at 10am', 'ham', 0.02, NOW(), false),
(1, 'You have been selected for a free iPhone 15. Reply YES to claim.', 'spam', 0.98, NOW(), false),
(1, 'Can you send me the report by end of day?', 'ham', 0.01, NOW(), false),
(1, 'Win a brand new car! Enter our sweepstakes today, absolutely FREE!', 'spam', 0.96, NOW(), false),
(1, 'The project deadline has been moved to next Friday.', 'ham', 0.03, NOW(), false),
(1, 'Your PayPal account is limited. Log in now to restore access.', 'spam', 0.94, NOW(), false),
(1, 'Did you get a chance to review my pull request?', 'ham', 0.02, NOW(), false),
(1, 'Earn $500 a day working from home! No experience needed!', 'spam', 0.99, NOW(), false),
(1, 'Groceries list: milk, eggs, bread, apples.', 'ham', 0.01, NOW(), false),
(1, 'FINAL NOTICE: Your loan application is approved. Claim $50,000 now.', 'spam', 0.97, NOW(), false),
(1, 'Mom said dinner is at 7pm tonight.', 'ham', 0.01, NOW(), false),
(1, 'Exclusive offer! Buy 2 get 3 free on all supplements. Limited time!', 'spam', 0.91, NOW(), false),
(1, 'Please find attached the invoice for last month.', 'ham', 0.02, NOW(), false),
(9, 'You are the lucky winner of our weekly lottery! Claim your prize.', 'spam', 0.98, NOW(), false),
(9, 'The Wi-Fi password at the office has been changed to office2026.', 'ham', 0.03, NOW(), false),
(10, 'Hot singles in your area are waiting to chat with you!', 'spam', 0.95, NOW(), false),
(10, 'Can we reschedule tomorrows meeting to 3pm?', 'ham', 0.02, NOW(), false),
(11, 'Claim your free gift card worth $250 — survey takes only 2 minutes!', 'spam', 0.93, NOW(), false),
(11, 'Just wanted to check in and see how youre doing.', 'ham', 0.01, NOW(), false),
(12, 'Your bank account has been suspended. Click here to verify.', 'spam', 0.97, NOW(), false),
(12, 'The conference room is booked for 9am tomorrow.', 'ham', 0.02, NOW(), false),
(13, 'Make money fast! Join our crypto investment platform today.', 'spam', 0.96, NOW(), false),
(13, 'Happy birthday! Hope you have a great day.', 'ham', 0.01, NOW(), false),
(14, 'You have a pending package delivery. Pay $2 to release it.', 'spam', 0.94, NOW(), false),
(14, 'Reminder: dentist appointment on Wednesday at 2pm.', 'ham', 0.01, NOW(), false),
(15, 'Increase your credit score by 200 points in 30 days — guaranteed!', 'spam', 0.92, NOW(), false),
(15, 'I left my charger at your place, can I pick it up later?', 'ham', 0.02, NOW(), false),
(16, 'FREE weight loss pills! Lose 20 lbs in 2 weeks, no diet needed.', 'spam', 0.98, NOW(), false),
(16, 'The client meeting notes have been shared on Google Drive.', 'ham', 0.02, NOW(), false),
(17, 'Your Microsoft subscription has expired. Renew now to avoid data loss.', 'spam', 0.95, NOW(), false),
(17, 'Ill be a bit late to the office, probably around 10am.', 'ham', 0.03, NOW(), false),
(18, 'You have been pre-selected for a platinum credit card. Apply now!', 'spam', 0.91, NOW(), false),
(18, 'Thanks for the help yesterday, really appreciate it.', 'ham', 0.01, NOW(), false),
(1, 'You have won a luxury cruise for two! Call now to claim your prize.', 'spam', 0.97, NOW(), false),
(1, 'Can you pick up the kids from school today?', 'ham', 0.01, NOW(), false),
(1, 'LIMITED OFFER: Get 90% off on designer watches today only!', 'spam', 0.96, NOW(), false),
(1, 'The new employee onboarding is scheduled for Monday at 9am.', 'ham', 0.02, NOW(), false),
(1, 'Your tax refund of $3,200 is ready. Click to receive via wire transfer.', 'spam', 0.98, NOW(), false),
(1, 'Do not forget about the team lunch on Thursday.', 'ham', 0.01, NOW(), false),
(1, 'Act now! Refinance your mortgage and save thousands every year.', 'spam', 0.93, NOW(), false),
(1, 'Your package has been delivered to the front door.', 'ham', 0.02, NOW(), false),
(1, 'Congratulations! Your email was selected for a $500 Amazon voucher.', 'spam', 0.97, NOW(), false),
(1, 'Please review the attached contract before signing.', 'ham', 0.02, NOW(), false),
(1, 'You qualify for a government grant of $10,000. Apply before midnight!', 'spam', 0.95, NOW(), false),
(1, 'Heading to the gym after work, want to join?', 'ham', 0.01, NOW(), false),
(1, 'Buy cheap prescription meds online — no doctor needed!', 'spam', 0.99, NOW(), false),
(1, 'I have uploaded the final presentation to SharePoint.', 'ham', 0.02, NOW(), false),
(1, 'Double your investment in 48 hours with our AI trading bot.', 'spam', 0.98, NOW(), false),
(1, 'The heating in the office is broken, please wear warm clothes.', 'ham', 0.01, NOW(), false),
(1, 'FREE casino chips! Sign up now and get $1000 bonus instantly.', 'spam', 0.96, NOW(), false),
(1, 'Could you send me the login credentials for the staging server?', 'ham', 0.03, NOW(), false),
(1, 'Your Netflix account will be cancelled unless you update payment now.', 'spam', 0.94, NOW(), false),
(1, 'The quarterly report is ready for your review.', 'ham', 0.02, NOW(), false),
(1, 'Earn passive income by sharing our link — $50 per referral!', 'spam', 0.92, NOW(), false),
(1, 'Book club meeting moved to next Tuesday at 7pm.', 'ham', 0.01, NOW(), false),
(1, 'Your Apple ID has been locked. Verify immediately to unlock.', 'spam', 0.97, NOW(), false),
(1, 'Just sent you the files you asked for via email.', 'ham', 0.01, NOW(), false),
(1, 'Get rich quick! Our members earn $1,000 daily with zero effort.', 'spam', 0.99, NOW(), false),
(1, 'Annual company picnic is on June 14th at Riverside Park.', 'ham', 0.01, NOW(), false),
(1, 'Cheap flights to Miami — book now before prices go up!', 'spam', 0.89, NOW(), false),
(1, 'The server maintenance window is tonight from 2am to 4am.', 'ham', 0.02, NOW(), false),
(1, 'Claim your unclaimed inheritance of $4.5 million today.', 'spam', 0.99, NOW(), false),
(1, 'Can you proofread this email before I send it to the client?', 'ham', 0.02, NOW(), false),
(1, 'Work from home and earn $2000/week — no experience required!', 'spam', 0.96, NOW(), false),
(1, 'The new parking passes are available at reception.', 'ham', 0.01, NOW(), false),
(1, 'Your DHL shipment is on hold. Pay customs fee of $4.99 now.', 'spam', 0.94, NOW(), false),
(1, 'See you at the conference next week in Chicago!', 'ham', 0.01, NOW(), false),
(1, 'Exclusive investment opportunity — guaranteed 300% returns!', 'spam', 0.97, NOW(), false),
(1, 'The coffee machine on the 3rd floor is fixed.', 'ham', 0.01, NOW(), false),
(1, 'You have been charged $299 for a subscription. To cancel click here.', 'spam', 0.95, NOW(), false),
(1, 'Great job on the presentation today, the client was impressed.', 'ham', 0.01, NOW(), false),
(1, 'Download our app and spin to win cash prizes every day!', 'spam', 0.93, NOW(), false),
(1, 'I will be working from home tomorrow if you need to reach me.', 'ham', 0.02, NOW(), false);
