version: "3.8"

services:
  consul:
    image: consul:1.15
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0
    networks:
      - microservices-net

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - microservices-net

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8085:80"
    networks:
      - microservices-net

  spam-history-service:
    build:
      context: ./microservices/quarkus
      dockerfile: Dockerfile
    image: quarkus-app:latest
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://mysql:3306/mydb
      QUARKUS_DATASOURCE_USERNAME: user
      QUARKUS_DATASOURCE_PASSWORD: password
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    networks:
      - microservices-net
    depends_on:
      - mysql
      - consul
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  spam-detection-service:
    build:
      context: ./spam-fast-api
      dockerfile: Dockerfile
    image: spam-detection-service:latest
    expose:
      - "8000"
    environment:
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    networks:
      - microservices-net
    depends_on:
      - consul
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: api-gateway:latest
    ports:
      - "8080:8080"
    environment:
      SPAM_SERVICE_URL: http://spam-detection-service:8000
      SPAM_HISTORY_SERVICE_URL: http://spam-history-service:8082
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      USER_SERVICE_URL: http://user-service:8081
      JWT_SECRET: sakldjasjfldkjgaosdifjdnasldkjaslkdjaslkdjfdsfuoasilkjdm
    networks:
      - microservices-net
    depends_on:
      - spam-detection-service
      - consul
      - user-service
      - spam-history-service

  mysql-users:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_users_data:/var/lib/mysql
      - ./mysql-users-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - microservices-net

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: user-service:latest
    expose:
      - "8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-users:3306/users_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    networks:
      - microservices-net
    depends_on:
      - mysql-users
      - consul
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    build:
      context: ./frontend/microservices-front
      dockerfile: Dockerfile
    image: frontend-app:latest
    ports:
      - "4200:80"
    networks:
      - microservices-net
    depends_on:
      - api-gateway

networks:
  microservices-net:

volumes:
  mysql_users_data:
  mysql_data:
