server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      ribbon:
         enabled: false
      config:
        default:
          hint: round_robin
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: api-gateway
        instance-id: api-gateway-1
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # SPAM DETECTION
        - id: spam-detection-service
          uri: lb://spam-detection-service
          predicates:
            - Path=/spam/**
          filters:
            - StripPrefix=1

        # SPAM HISTORY 
        - id: spam-history-service
          uri: lb://spam-history-service
          predicates:
            - Path=/history/**
          filters:
            - StripPrefix=1

        # USER SERVICE
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1

jwt:
  secret: abcddsdasdsaabcddsdasdsaabcddsdasdsaabcddsdasdsalwqiepowaskdl
  expiration: 86400000

# configuration for actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
