micronaut.application.name=micronaut-service
micronaut.server.port=8081

consul.client.host=consul
consul.client.port=8500
consul.client.registration.enabled=true

consul.client.registration.check.enabled=true
consul.client.registration.check.http=true
consul.client.registration.check.path=/health
consul.client.registration.check.interval=10s