quarkus.application.name=quarkus-service
quarkus.http.host=0.0.0.0
quarkus.http.port=8082

consul.host=consul
consul.port=8500

quarkus.datasource.db-kind=mysql
quarkus.datasource.username-file=${QUARKUS_DATASOURCE_USERNAME_FILE}
quarkus.datasource.password-file=${QUARKUS_DATASOURCE_PASSWORD_FILE}
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL}