quarkus.application.name=quarkus-service
quarkus.http.host=0.0.0.0
quarkus.http.port=8082

consul.host=consul
consul.port=8500
service.address=spam-history-service

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME_FILE}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD_FILE}
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL}

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.packages=com.example

quarkus.otel.enabled=${QUARKUS_OTEL_ENABLED}
quarkus.otel.exporter.otlp.endpoint=${QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT}
quarkus.otel.exporter.otlp.protocol=${QUARKUS_OTEL_EXPORTER_OTLP_PROTOCOL}
quarkus.otel.traces.sampler=${QUARKUS_OTEL_TRACES_SAMPLER}
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n

